---
title: "Business Problem"
author: "Alex Aronson"
date: "`r Sys.Date()`"
output: html_document
---

**.Using the pedestrian.csv data set, train a GLM using a Poisson distribution with log link function to identify and interpret factors that relate to higher or lower counts of pedestrians.**

```{R}
library(dplyr)
library(ggplot2)
ped<- read.csv("pedestrian.csv")
head(ped)
str(ped)

```

```{R}

ped$weather<- as.factor(ped$weather)
ped$weekday<- as.factor(ped$weekday)
head(ped)
str(ped)

```

**Building Model/Exploring Data.**

```{R}

ped.aov<- aov(pedestrians~.,data=ped)
summary(ped.aov)

```
 
  - I chose to take look at an ANOVA summary using all factors in order to see which ones were potentially insignificant on a $\alpha=0.05$ level, as we can see from the summary it looks like every factor in the data set has a significant effect on the outcome of pedestrian traffic.

```{R}
# checking continuous variables

cont<- select_if(ped, is.numeric)
summary(cont)

```
```{R}
# Visualizing Variables vs Pedestrians data 
library(ggplot2)

ggplot(ped, aes(temperature, pedestrians)) +geom_point() +  geom_smooth()
ggplot(ped, aes(hour, pedestrians)) +geom_point() +  geom_smooth()
ggplot(ped, aes(precipitation, pedestrians)) +geom_point() +  geom_smooth()
ggplot(ped, aes(temp_forecast, pedestrians)) +geom_point() +  geom_smooth()

```



```{R}

# splitting data 

training<- ped %>% dplyr::sample_frac(0.8)
dim(training)

testing<- dplyr::anti_join(ped, training, by='pedestrians')
dim(testing)
```

```{R}

# modeling data

mod<- glm(pedestrians ~ ., data= training, family = poisson(link="log"))
summary(mod)
coef(mod)

```

```{R}
# running predictions of testing data. 

testing$predictions<- predict(mod, newdata=testing, type="response",se.fit=FALSE)
head(testing)

```



```{R}


mod2<- glm(pedestrians~.,family= poisson(link = "log"), data = ped )
summary(ped)

ped$predicted<- predict(mod2, data= ped, type="response")
head(ped)

```

  - Looking at the data both split and non-split we can see that factors that mostly contribute to low numbers are rain/snow, cold, and night time, whereas high pedestrian numbers are seen during warm, clear/cloudy, no precipitation and during the day. Lastly weekday doesn't seem to have a significant effect. 


```{R}
ped %>% 
  group_by(hour) %>% 
  summarise(sum(pedestrians))

ped %>%
  group_by(weekday) %>%
  summarise(sum(pedestrians))
```

```{R}

ped %>%
  group_by(hour) %>% 
  summarise(Actual = sum(pedestrians),
            Predicted = sum(predicted)) %>% 
  ggplot(aes(x = hour)) +
        geom_line(aes(y = `Actual`), color = "purple", group = 1)+
        geom_line(aes(y = `Predicted`), color = "red", group = 1) + labs(title= "Actual vs. Predicted", x= "Hours Open", y= "Customer Foot Traffic")


ped %>%
  group_by(weekday) %>% 
  summarise(Actual = sum(pedestrians),
            Predicted = sum(predicted)) %>% 
  ggplot(aes(x = weekday)) +
        geom_line(aes(y = `Actual`), color = "green", group = 1)+
        geom_line(aes(y = `Predicted`), color = "orange", group = 1) + labs(title= "Actual vs. Predicted", x= "Day of the Week", y= "Customer Foot Traffic")



```

  - Looking at the line chart of Hours of operation and Day of the week(based on the model where splitting data isn't used) we see that the Mod2 is a good fit for days of the week, however if we look at hours of operation the model either slightly underestimates or overestimates the foot traffic. If we look instead at the split data, we may have a different outcome using the same graphs and factors.
  
  
```{R}

testing %>% 
  group_by(hour) %>% 
  summarise(sum(pedestrians))

testing %>%
  group_by(weekday) %>%
  summarise(sum(pedestrians))

testing %>%
  group_by(hour) %>% 
  summarise(Actual = sum(pedestrians),
            Predicted = sum(predictions)) %>% 
  ggplot(aes(x = hour)) +
        geom_line(aes(y = `Actual`), color = "purple", group = 1)+
        geom_line(aes(y = `Predicted`), color = "red", group = 1) + labs(title= "Actual vs. Predicted", x= "Hours Open", y= "Customer Foot Traffic")

testing %>%
  group_by(weekday) %>% 
  summarise(Actual = sum(pedestrians),
            Predicted = sum(predictions)) %>% 
  ggplot(aes(x = weekday)) +
        geom_line(aes(y = `Actual`), color = "green", group = 1)+
        geom_line(aes(y = `Predicted`), color = "orange", group = 1) + labs(title= "Actual vs. Predicted", x= "Day of the Week", y= "Customer Foot Traffic")

```



  - We can see that the testing model predicts that the day of the week and hour of operation both have an effect on foot traffic, and that the testing model under predicts in both cases. Having more foot traffic compared to the model is not a bad thing, however we would want our model to be as accurate as possible, so using an 80/20 split may not produce the most favorable results. 


