---
title: "Exploritory Data Analysis"
author: "Alex Aronson"
date: "`r Sys.Date()`"
output: html_document
---
**1. Loading the Data into R and assigning it the name TI. 2. Running "summary()" function to display stats of data frame.**
```{R}
TI <- read.csv("titanic.csv")
summary(TI)
head(TI)
```
**2.1 Visualization of the stats using ggplot() function for different graphs of the data, as well as cleaning data.**
```{R}
library(dplyr)
TI <- TI %>%
  mutate(Age_new = factor(ifelse(is.na(Age), "unknown", Age)))
summary(TI$Age_new)
```
Since the original data frame shows that there is 177 passengers that are considered NA's( which makes up ~20% of passengers), we would consider that a significant amount of data that has no classification. So we would choose to handle it as in the module example, and convert the data to a category called unknown. That way we can still include the data in the model. 

  b.looking Age distribution of passengers based on original data.
```{R}
library(ggplot2)

ggplot(TI, aes(x=Age), na.rm=TRUE) + geom_histogram(aes(y = ..density..), binwidth = 5, color = "black", fill = "white",lwd=1,na.rm=TRUE) +geom_density(color="red", lwd=1,fill= "red",alpha=.25, na.rm=TRUE) + theme_classic() + ggtitle("Titanic Age Distribution") +
  scale_x_continuous(name= "Passenger Age", breaks = 5*c(0:18)) +
  scale_y_continuous(name = "Passenger Count") 

```
```{R}
mean(TI$Age, na.rm=TRUE)
```
Looking at the Age distribution, and ignoring the NA values we can see that the average age is ~30 of all passengers aboard the ship. 

  c. Looking at the survival rate of the passengers based on age from original data and ignoring NA's
```{R}
library(ggplot2)
library(dplyr)

TI <- TI %>%
  mutate(Survived = factor(Survived)) 
         
ggplot(TI) +geom_histogram(aes(x = Age, fill = Survived), binwidth = 5, color = "Black",na.rm=TRUE) + theme_classic() + ggtitle("Titanic Survival Rate by Age") +
  scale_x_continuous(name= "Passenger Age", breaks = 5*c(0:18)) +
  scale_y_continuous(name = "Passenger Count") +
  scale_fill_discrete(labels = c("Did Not Survive", "Survived"))
```


```{R}
library(ggplot2)
library(dplyr)

TI %>%
  ggplot() + geom_bar(aes(x = Sex, fill = Survived)) + theme_classic() + ggtitle("Titanic Gender Survival Rate") +
  scale_x_discrete(name= "Sex") +
  scale_y_continuous(name = "Passenger Count") +
  scale_fill_discrete(name = "Outcome", labels = c("Did Not Survive", "Survived"))
```
  
  Firstly, any variable that is categorical must be converted to a factor if possible, or else it will not graph properly, I found this out through lots of trial and error, as well as looking back at my Intro to R projects. Nonetheless, when we use "Survived" as a fill for the histogram, we can see that by in large the age group that did not survive is consistent with the mean age group of passengers aboard the ship. This is of course neglecting to include the NA values of 177. Which unfortunately makes graphing a little more difficult. Furthermore, looking at Survived vs Sex we see that Females had a better chance of survival as well. 

**3. Are there variables with missing values, and how would you handle them and why?**
  
  Yes, there are 177 NA values under the Age column. As previously stated, because the amount is significant for the amount of data we are given, we have to treat it as necessary for part of the modeling. So we previously referenced the lessons and converted the values to a new category named unknown.

**4. Describe the relationship of the target variable (Survived) with the rest of the predictors. Is there any insight you were able to obtain? For example, what are the variables that seem to be predictive of someone surviving the titanic or not?**
  
  I chose to look at specifically Age and Sex as predictors against Survived, in doing so we can extrapolate that of the people that did survive, they tended to be around the age group of 30, and mostly female. 
  
**Feature engineering. Can you create a new possible predictor from the existing predictors?**

  Yes we could create a new predictor based on the size of families on board. using the code below and displaying the new dataframe. 
  
```{R}
library(dplyr)
library(ggplot2)

TI <- TI %>%
  mutate(FamilySize = 1 + SibSp + Parch)
head(TI)
```

  We can also graph each of the classes, male and female, and whether they survived using the facet function from ch.3 in "Practical Data Science with R"

```{R}
TI %>%
  ggplot() + geom_histogram(aes(x = FamilySize, fill = Survived), binwidth = 1) + facet_grid(Sex ~ Pclass) +ggtitle("Survival by Family Size") +
  scale_x_continuous(name = "Family Size") +
  scale_y_continuous(name = "Passenger Count") +
  scale_fill_discrete(name = "Outcome", labels = c("Did Not Survive", "Survived"))
```

  

  








